/**
 * lib/server/device-db.ts  — SERVER ONLY
 *
 * قاعدة بيانات شاملة للأجهزة مع الـ codenames الرسمية
 * كل جهاز له: codename، اسم، brand، aliases، variant words
 */

export interface DeviceEntry {
  codename: string;       // الكودنيم الرسمي: "rodin"
  displayName: string;    // "Poco X7 Pro"
  brand: string;          // "Xiaomi"
  aliases: string[];      // أشكال بديلة يكتبها الناس
  variantWords: string[]; // الكلمات المميِّزة: ["x7", "pro"]
  released: string;       // "2025"
  chipset?: string;
  imageUrl?: string;      // صورة الجهاز (render)
}

export const DEVICE_DB: DeviceEntry[] = [
  // ─── Xiaomi / POCO / Redmi ─────────────────────────────────────────────
  {
    codename: "rodin",
    displayName: "Poco X7 Pro",
    brand: "Xiaomi",
    aliases: ["pocox7pro", "poco x7 pro", "x7 pro poco"],
    variantWords: ["x7", "pro"],
    released: "2025",
    chipset: "Dimensity 8400-Ultra",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-poco-x7-pro.jpg",
  },
  {
    codename: "ice",
    displayName: "Poco X7",
    brand: "Xiaomi",
    aliases: ["pocox7", "poco x7"],
    variantWords: ["x7"],
    released: "2025",
    chipset: "Dimensity 7300 Ultra",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-poco-x7.jpg",
  },
  {
    codename: "duchesse",
    displayName: "Poco X6 Pro",
    brand: "Xiaomi",
    aliases: ["pocox6pro", "poco x6 pro"],
    variantWords: ["x6", "pro"],
    released: "2024",
    chipset: "Dimensity 8300",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-poco-x6-pro.jpg",
  },
  {
    codename: "pissarro",
    displayName: "Poco X6",
    brand: "Xiaomi",
    aliases: ["pocox6", "poco x6"],
    variantWords: ["x6"],
    released: "2024",
    chipset: "Dimensity 6080",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-poco-x6.jpg",
  },
  {
    codename: "redwood",
    displayName: "Poco X5 Pro",
    brand: "Xiaomi",
    aliases: ["pocox5pro", "poco x5 pro"],
    variantWords: ["x5", "pro"],
    released: "2023",
    chipset: "Snapdragon 778G",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-poco-x5-pro.jpg",
  },
  {
    codename: "moonstone",
    displayName: "Poco X5",
    brand: "Xiaomi",
    aliases: ["pocox5", "poco x5"],
    variantWords: ["x5"],
    released: "2023",
    chipset: "Snapdragon 695",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-poco-x5.jpg",
  },
  {
    codename: "vermeer",
    displayName: "Poco F6 Pro",
    brand: "Xiaomi",
    aliases: ["pocof6pro", "poco f6 pro"],
    variantWords: ["f6", "pro"],
    released: "2024",
    chipset: "Snapdragon 8 Gen 2",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-poco-f6-pro.jpg",
  },
  {
    codename: "peridot",
    displayName: "Poco F6",
    brand: "Xiaomi",
    aliases: ["pocof6", "poco f6"],
    variantWords: ["f6"],
    released: "2024",
    chipset: "Snapdragon 8s Gen 3",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-poco-f6.jpg",
  },
  {
    codename: "mondrian",
    displayName: "Poco F5 Pro",
    brand: "Xiaomi",
    aliases: ["pocof5pro", "poco f5 pro"],
    variantWords: ["f5", "pro"],
    released: "2023",
    chipset: "Snapdragon 8+ Gen 1",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-poco-f5-pro.jpg",
  },
  {
    codename: "marble",
    displayName: "Poco F5",
    brand: "Xiaomi",
    aliases: ["pocof5", "poco f5"],
    variantWords: ["f5"],
    released: "2023",
    chipset: "Snapdragon 7+ Gen 2",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-poco-f5.jpg",
  },
  {
    codename: "aurora",
    displayName: "Poco M6 Pro",
    brand: "Xiaomi",
    aliases: ["pocom6pro", "poco m6 pro"],
    variantWords: ["m6", "pro"],
    released: "2024",
    chipset: "Helio G99 Ultra",
  },
  {
    codename: "citrus",
    displayName: "Poco M5s",
    brand: "Xiaomi",
    aliases: ["pocom5s", "poco m5s"],
    variantWords: ["m5", "s"],
    released: "2022",
    chipset: "Helio G95",
  },

  // Redmi Note series
  {
    codename: "zircon",
    displayName: "Redmi Note 14 Pro+",
    brand: "Xiaomi",
    aliases: ["redmi note 14 pro plus", "redmi note14 pro+", "note 14 pro+"],
    variantWords: ["note", "14", "pro", "plus"],
    released: "2025",
    chipset: "Dimensity 9200+",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-14-pro-.jpg",
  },
  {
    codename: "swift",
    displayName: "Redmi Note 14 Pro",
    brand: "Xiaomi",
    aliases: ["redmi note 14 pro", "note 14 pro"],
    variantWords: ["note", "14", "pro"],
    released: "2025",
    chipset: "Dimensity 7300 Ultra",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-14-pro.jpg",
  },
  {
    codename: "jade",
    displayName: "Redmi Note 14",
    brand: "Xiaomi",
    aliases: ["redmi note 14", "note 14"],
    variantWords: ["note", "14"],
    released: "2025",
    chipset: "Snapdragon 4s Gen 2",
  },
  {
    codename: "garnet",
    displayName: "Redmi Note 13 Pro+",
    brand: "Xiaomi",
    aliases: ["redmi note 13 pro plus", "note 13 pro+"],
    variantWords: ["note", "13", "pro", "plus"],
    released: "2024",
    chipset: "Dimensity 1200 Ultra",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-13-pro-.jpg",
  },
  {
    codename: "emerald",
    displayName: "Redmi Note 13 Pro",
    brand: "Xiaomi",
    aliases: ["redmi note 13 pro", "note 13 pro"],
    variantWords: ["note", "13", "pro"],
    released: "2024",
    chipset: "Snapdragon 7s Gen 2",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-13-pro.jpg",
  },
  {
    codename: "sapphire",
    displayName: "Redmi Note 13",
    brand: "Xiaomi",
    aliases: ["redmi note 13", "note 13"],
    variantWords: ["note", "13"],
    released: "2024",
    chipset: "Snapdragon 685",
  },
  {
    codename: "ruby",
    displayName: "Redmi Note 12 Pro+",
    brand: "Xiaomi",
    aliases: ["redmi note 12 pro plus", "note 12 pro+"],
    variantWords: ["note", "12", "pro", "plus"],
    released: "2023",
    chipset: "Dimensity 1080",
  },
  {
    codename: "ruby",
    displayName: "Redmi Note 12 Pro",
    brand: "Xiaomi",
    aliases: ["redmi note 12 pro", "note 12 pro"],
    variantWords: ["note", "12", "pro"],
    released: "2023",
    chipset: "Dimensity 1080",
  },
  {
    codename: "tapas",
    displayName: "Redmi Note 12",
    brand: "Xiaomi",
    aliases: ["redmi note 12", "note 12"],
    variantWords: ["note", "12"],
    released: "2023",
    chipset: "Snapdragon 685",
  },

  // Xiaomi numbered series
  {
    codename: "corot",
    displayName: "Xiaomi 15",
    brand: "Xiaomi",
    aliases: ["mi 15", "xiaomi15"],
    variantWords: ["15"],
    released: "2025",
    chipset: "Snapdragon 8 Elite",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-15.jpg",
  },
  {
    codename: "diting",
    displayName: "Xiaomi 14T Pro",
    brand: "Xiaomi",
    aliases: ["xiaomi 14t pro", "mi 14t pro"],
    variantWords: ["14t", "pro"],
    released: "2024",
    chipset: "Dimensity 9300+",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-14t-pro.jpg",
  },
  {
    codename: "liuqin",
    displayName: "Xiaomi 14T",
    brand: "Xiaomi",
    aliases: ["xiaomi 14t", "mi 14t"],
    variantWords: ["14t"],
    released: "2024",
    chipset: "Dimensity 8300 Ultra",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-14t.jpg",
  },
  {
    codename: "shennong",
    displayName: "Xiaomi 14 Pro",
    brand: "Xiaomi",
    aliases: ["mi 14 pro", "xiaomi14pro"],
    variantWords: ["14", "pro"],
    released: "2024",
    chipset: "Snapdragon 8 Gen 3",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-14-pro.jpg",
  },
  {
    codename: "houji",
    displayName: "Xiaomi 14",
    brand: "Xiaomi",
    aliases: ["mi 14", "xiaomi14"],
    variantWords: ["14"],
    released: "2024",
    chipset: "Snapdragon 8 Gen 3",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-14.jpg",
  },
  {
    codename: "nuwa",
    displayName: "Xiaomi 13 Pro",
    brand: "Xiaomi",
    aliases: ["mi 13 pro", "xiaomi13pro"],
    variantWords: ["13", "pro"],
    released: "2023",
    chipset: "Snapdragon 8 Gen 2",
  },
  {
    codename: "fuxi",
    displayName: "Xiaomi 13",
    brand: "Xiaomi",
    aliases: ["mi 13", "xiaomi13"],
    variantWords: ["13"],
    released: "2023",
    chipset: "Snapdragon 8 Gen 2",
  },

  // ─── Samsung ───────────────────────────────────────────────────────────
  {
    codename: "bov",
    displayName: "Galaxy S25 Ultra",
    brand: "Samsung",
    aliases: ["samsung galaxy s25 ultra", "s25 ultra", "galaxy s25 ultra"],
    variantWords: ["s25", "ultra"],
    released: "2025",
    chipset: "Snapdragon 8 Elite",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s25-ultra.jpg",
  },
  {
    codename: "boc",
    displayName: "Galaxy S25+",
    brand: "Samsung",
    aliases: ["samsung galaxy s25 plus", "s25 plus", "s25+"],
    variantWords: ["s25", "plus"],
    released: "2025",
    chipset: "Snapdragon 8 Elite",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s25-.jpg",
  },
  {
    codename: "boe",
    displayName: "Galaxy S25",
    brand: "Samsung",
    aliases: ["samsung galaxy s25", "galaxy s25"],
    variantWords: ["s25"],
    released: "2025",
    chipset: "Snapdragon 8 Elite",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s25.jpg",
  },
  {
    codename: "e3q",
    displayName: "Galaxy S24 Ultra",
    brand: "Samsung",
    aliases: ["samsung galaxy s24 ultra", "s24 ultra"],
    variantWords: ["s24", "ultra"],
    released: "2024",
    chipset: "Snapdragon 8 Gen 3",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s24-ultra.jpg",
  },
  {
    codename: "b0q",
    displayName: "Galaxy S24+",
    brand: "Samsung",
    aliases: ["samsung galaxy s24 plus", "s24+"],
    variantWords: ["s24", "plus"],
    released: "2024",
    chipset: "Exynos 2400 / Snapdragon 8 Gen 3",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s24-.jpg",
  },
  {
    codename: "b0s",
    displayName: "Galaxy S24",
    brand: "Samsung",
    aliases: ["samsung galaxy s24", "galaxy s24"],
    variantWords: ["s24"],
    released: "2024",
    chipset: "Exynos 2400 / Snapdragon 8 Gen 3",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s24.jpg",
  },
  {
    codename: "gts9",
    displayName: "Galaxy S23 Ultra",
    brand: "Samsung",
    aliases: ["samsung galaxy s23 ultra", "s23 ultra"],
    variantWords: ["s23", "ultra"],
    released: "2023",
    chipset: "Snapdragon 8 Gen 2",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s23-ultra.jpg",
  },
  {
    codename: "q5q",
    displayName: "Galaxy Z Fold 6",
    brand: "Samsung",
    aliases: ["galaxy z fold6", "z fold 6"],
    variantWords: ["z", "fold", "6"],
    released: "2024",
    chipset: "Snapdragon 8 Gen 3",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-z-fold6.jpg",
  },
  {
    codename: "b5q",
    displayName: "Galaxy Z Flip 6",
    brand: "Samsung",
    aliases: ["galaxy z flip6", "z flip 6"],
    variantWords: ["z", "flip", "6"],
    released: "2024",
    chipset: "Snapdragon 8 Gen 3",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-z-flip6.jpg",
  },
  {
    codename: "a55x",
    displayName: "Galaxy A55",
    brand: "Samsung",
    aliases: ["samsung galaxy a55", "galaxy a55"],
    variantWords: ["a55"],
    released: "2024",
    chipset: "Exynos 1480",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a55.jpg",
  },
  {
    codename: "a35x",
    displayName: "Galaxy A35",
    brand: "Samsung",
    aliases: ["samsung galaxy a35", "galaxy a35"],
    variantWords: ["a35"],
    released: "2024",
    chipset: "Exynos 1380",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a35.jpg",
  },
  {
    codename: "a16x",
    displayName: "Galaxy A16",
    brand: "Samsung",
    aliases: ["samsung galaxy a16", "galaxy a16"],
    variantWords: ["a16"],
    released: "2024",
    chipset: "Helio G99",
  },

  // ─── OnePlus ───────────────────────────────────────────────────────────
  {
    codename: "odin3",
    displayName: "OnePlus 13",
    brand: "OnePlus",
    aliases: ["op13", "oneplus13", "1+13"],
    variantWords: ["13"],
    released: "2025",
    chipset: "Snapdragon 8 Elite",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/oneplus-13.jpg",
  },
  {
    codename: "waffle",
    displayName: "OnePlus 12",
    brand: "OnePlus",
    aliases: ["op12", "oneplus12", "1+12"],
    variantWords: ["12"],
    released: "2024",
    chipset: "Snapdragon 8 Gen 3",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/oneplus-12.jpg",
  },
  {
    codename: "salami",
    displayName: "OnePlus 11",
    brand: "OnePlus",
    aliases: ["op11", "oneplus11", "1+11"],
    variantWords: ["11"],
    released: "2023",
    chipset: "Snapdragon 8 Gen 2",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/oneplus-11.jpg",
  },
  {
    codename: "aston",
    displayName: "OnePlus Open",
    brand: "OnePlus",
    aliases: ["oneplus open", "op open"],
    variantWords: ["open"],
    released: "2023",
    chipset: "Snapdragon 8 Gen 2",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/oneplus-open.jpg",
  },
  {
    codename: "ban",
    displayName: "OnePlus Nord 4",
    brand: "OnePlus",
    aliases: ["oneplus nord4", "nord 4"],
    variantWords: ["nord", "4"],
    released: "2024",
    chipset: "Snapdragon 7+ Gen 3",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/oneplus-nord-4.jpg",
  },
  {
    codename: "ivan",
    displayName: "OnePlus Nord CE4",
    brand: "OnePlus",
    aliases: ["nord ce 4", "nordce4"],
    variantWords: ["nord", "ce", "4"],
    released: "2024",
    chipset: "Snapdragon 7s Gen 2",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/oneplus-nord-ce-4.jpg",
  },

  // ─── Google Pixel ──────────────────────────────────────────────────────
  {
    codename: "komodo",
    displayName: "Pixel 9 Pro XL",
    brand: "Google",
    aliases: ["google pixel 9 pro xl", "pixel9 pro xl"],
    variantWords: ["9", "pro", "xl"],
    released: "2024",
    chipset: "Tensor G4",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-9-pro-xl.jpg",
  },
  {
    codename: "caiman",
    displayName: "Pixel 9 Pro",
    brand: "Google",
    aliases: ["google pixel 9 pro", "pixel9pro"],
    variantWords: ["9", "pro"],
    released: "2024",
    chipset: "Tensor G4",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-9-pro.jpg",
  },
  {
    codename: "comet",
    displayName: "Pixel 9 Pro Fold",
    brand: "Google",
    aliases: ["pixel 9 pro fold", "pixel9 pro fold"],
    variantWords: ["9", "pro", "fold"],
    released: "2024",
    chipset: "Tensor G4",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-9-pro-fold.jpg",
  },
  {
    codename: "tokay",
    displayName: "Pixel 9",
    brand: "Google",
    aliases: ["google pixel 9", "pixel9"],
    variantWords: ["9"],
    released: "2024",
    chipset: "Tensor G4",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-9.jpg",
  },
  {
    codename: "husky",
    displayName: "Pixel 8 Pro",
    brand: "Google",
    aliases: ["google pixel 8 pro", "pixel8pro"],
    variantWords: ["8", "pro"],
    released: "2023",
    chipset: "Tensor G3",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-8-pro.jpg",
  },
  {
    codename: "shiba",
    displayName: "Pixel 8",
    brand: "Google",
    aliases: ["google pixel 8", "pixel8"],
    variantWords: ["8"],
    released: "2023",
    chipset: "Tensor G3",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-8.jpg",
  },
  {
    codename: "akita",
    displayName: "Pixel 8a",
    brand: "Google",
    aliases: ["google pixel 8a", "pixel8a"],
    variantWords: ["8a"],
    released: "2024",
    chipset: "Tensor G3",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-8a.jpg",
  },
  {
    codename: "cheetah",
    displayName: "Pixel 7 Pro",
    brand: "Google",
    aliases: ["google pixel 7 pro", "pixel7pro"],
    variantWords: ["7", "pro"],
    released: "2022",
    chipset: "Tensor G2",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-7-pro.jpg",
  },
  {
    codename: "panther",
    displayName: "Pixel 7",
    brand: "Google",
    aliases: ["google pixel 7", "pixel7"],
    variantWords: ["7"],
    released: "2022",
    chipset: "Tensor G2",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-7.jpg",
  },
  {
    codename: "lynx",
    displayName: "Pixel 7a",
    brand: "Google",
    aliases: ["google pixel 7a", "pixel7a"],
    variantWords: ["7a"],
    released: "2023",
    chipset: "Tensor G2",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-7a.jpg",
  },
  {
    codename: "raven",
    displayName: "Pixel 6 Pro",
    brand: "Google",
    aliases: ["google pixel 6 pro", "pixel6pro"],
    variantWords: ["6", "pro"],
    released: "2021",
    chipset: "Tensor G1",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-6-pro.jpg",
  },
  {
    codename: "oriole",
    displayName: "Pixel 6",
    brand: "Google",
    aliases: ["google pixel 6", "pixel6"],
    variantWords: ["6"],
    released: "2021",
    chipset: "Tensor G1",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-6.jpg",
  },
  {
    codename: "bluejay",
    displayName: "Pixel 6a",
    brand: "Google",
    aliases: ["google pixel 6a", "pixel6a"],
    variantWords: ["6a"],
    released: "2022",
    chipset: "Tensor G1",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-6a.jpg",
  },

  // ─── Nothing ───────────────────────────────────────────────────────────
  {
    codename: "tetris",
    displayName: "Nothing Phone (2a) Plus",
    brand: "Nothing",
    aliases: ["nothing phone 2a plus", "phone (2a) plus"],
    variantWords: ["2a", "plus"],
    released: "2024",
    chipset: "Dimensity 7350 Pro",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/nothing-phone-2a-plus.jpg",
  },
  {
    codename: "pong",
    displayName: "Nothing Phone (2a)",
    brand: "Nothing",
    aliases: ["nothing phone 2a", "phone (2a)"],
    variantWords: ["2a"],
    released: "2024",
    chipset: "Dimensity 7200 Pro",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/nothing-phone-2a-.jpg",
  },
  {
    codename: "pong2",
    displayName: "Nothing Phone (2)",
    brand: "Nothing",
    aliases: ["nothing phone 2", "phone (2)"],
    variantWords: ["2"],
    released: "2023",
    chipset: "Snapdragon 8+ Gen 1",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/nothing-phone-2-.jpg",
  },
  {
    codename: "asterix",
    displayName: "Nothing Phone (1)",
    brand: "Nothing",
    aliases: ["nothing phone 1", "phone (1)"],
    variantWords: ["1"],
    released: "2022",
    chipset: "Snapdragon 778G+",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/nothing-phone-1-.jpg",
  },

  // ─── Realme ────────────────────────────────────────────────────────────
  {
    codename: "rmx3890",
    displayName: "Realme GT 7 Pro",
    brand: "Realme",
    aliases: ["realme gt7 pro", "gt 7 pro"],
    variantWords: ["gt", "7", "pro"],
    released: "2024",
    chipset: "Snapdragon 8 Elite",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/realme-gt-7-pro.jpg",
  },
  {
    codename: "rmx3741",
    displayName: "Realme GT 6",
    brand: "Realme",
    aliases: ["realme gt6", "gt 6"],
    variantWords: ["gt", "6"],
    released: "2024",
    chipset: "Snapdragon 8s Gen 3",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/realme-gt-6.jpg",
  },
  {
    codename: "rmx3840",
    displayName: "Realme 13 Pro+",
    brand: "Realme",
    aliases: ["realme 13 pro plus", "realme 13 pro+"],
    variantWords: ["13", "pro", "plus"],
    released: "2024",
    chipset: "Snapdragon 7s Gen 2",
  },
  {
    codename: "rmx3842",
    displayName: "Realme 13 Pro",
    brand: "Realme",
    aliases: ["realme 13 pro"],
    variantWords: ["13", "pro"],
    released: "2024",
    chipset: "Snapdragon 7s Gen 2",
  },

  // ─── Motorola ──────────────────────────────────────────────────────────
  {
    codename: "cancunf",
    displayName: "Motorola Edge 50 Pro",
    brand: "Motorola",
    aliases: ["moto edge 50 pro", "edge 50 pro"],
    variantWords: ["edge", "50", "pro"],
    released: "2024",
    chipset: "Snapdragon 7 Gen 3",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/motorola-edge-50-pro.jpg",
  },
  {
    codename: "cancunf_ultra",
    displayName: "Motorola Edge 50 Ultra",
    brand: "Motorola",
    aliases: ["moto edge 50 ultra"],
    variantWords: ["edge", "50", "ultra"],
    released: "2024",
    chipset: "Snapdragon 8s Gen 3",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/motorola-edge-50-ultra.jpg",
  },
  {
    codename: "sm8635",
    displayName: "Motorola Edge 50 Fusion",
    brand: "Motorola",
    aliases: ["moto edge 50 fusion", "edge 50 fusion"],
    variantWords: ["edge", "50", "fusion"],
    released: "2024",
    chipset: "Snapdragon 7s Gen 2",
  },

  // ─── ASUS ──────────────────────────────────────────────────────────────
  {
    codename: "ai2401",
    displayName: "ASUS Zenfone 11 Ultra",
    brand: "ASUS",
    aliases: ["zenfone 11 ultra", "zf11 ultra"],
    variantWords: ["zenfone", "11", "ultra"],
    released: "2024",
    chipset: "Snapdragon 8 Gen 3",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/asus-zenfone-11-ultra.jpg",
  },
  {
    codename: "ai2202",
    displayName: "ASUS ROG Phone 8 Pro",
    brand: "ASUS",
    aliases: ["rog phone 8 pro", "rog 8 pro"],
    variantWords: ["rog", "8", "pro"],
    released: "2024",
    chipset: "Snapdragon 8 Gen 3",
  imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/asus-rog-phone-8-pro.jpg",
  },
];

/** فهرس سريع: codename → DeviceEntry */
export const CODENAME_INDEX = new Map<string, DeviceEntry>(
  DEVICE_DB.map((d) => [d.codename.toLowerCase(), d])
);

/** فهرس سريع: alias → DeviceEntry */
export const ALIAS_INDEX = new Map<string, DeviceEntry>(
  DEVICE_DB.flatMap((d) =>
    d.aliases.map((a) => [a.toLowerCase().replace(/\s+/g, " ").trim(), d])
  )
);
